# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyShopping' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyShopping
  
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Firestore’
    pod 'Firebase/Messaging'
    pod 'IQKeyboardManagerSwift'
    pod 'Cosmos'
    pod 'ObjectMapper'
    pod 'GoogleMaps'
    pod 'SDWebImage/WebP'
end
